//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.11 at 09:12:37 PM IST 
//


package org.pushkal.JaxWS;

import java.math.BigInteger;
public class stock_online_req {

    protected BigInteger local_consulta;
    protected String lector;
    protected BigInteger sku_ean;

    /**
     * Gets the value of the localConsulta property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocal_consulta() {
        return local_consulta;
    }

    /**
     * Sets the value of the localConsulta property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocal_consulta(BigInteger value) {
        this.local_consulta = value;
    }

    /**
     * Gets the value of the lector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLector() {
        return lector;
    }

    /**
     * Sets the value of the lector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLector(String value) {
        this.lector = value;
    }

    /**
     * Gets the value of the skuEan property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSku_ean() {
        return sku_ean;
    }

    /**
     * Sets the value of the skuEan property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSku_ean(BigInteger value) {
        this.sku_ean = value;
    }

}
